name: Deploy to production
'on': [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: zendesk/checkout@v3
      - name: Setup Node.js
        uses: zendesk/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install node_modules
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Upload theme
        run: node ./bin/theme-upload.js
        env:
          ZENDESK_EMAIL: ${{ secrets.zendesk_email }}
          ZENDESK_API_TOKEN: ${{ secrets.zendesk_token }}
          ZENDESK_SUBDOMAIN: ${{ secrets.subdomain }}
