name: Deploy to Production
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        
      - name: Install ZCLI and Expect
        run: |
          npm install -g @zendesk/zcli
          sudo apt-get update && sudo apt-get install -y expect
          
      - name: Debug zcli login
        run: zcli login -i || true

      # Step 4: Automate ZCLI Login
      - name: ZCLI Login
        run: |
          chmod +x ./bin/zcli-login.expect
          ./bin/zcli-login.expect $ZENDESK_SUBDOMAIN $ZENDESK_EMAIL $ZENDESK_API_TOKEN
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
          
      - name: Test ZCLI Configuration
        run: zcli themes:list

      # Step 5: Upload and Publish Theme
      - name: Deploy Theme
        run: node ./bin/theme-upload.js
